In [2]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [3]:
data=pd.read_csv("C:/Users/Lenovo/OneDrive/Desktop/ds assignment dataset/Assignment3hyp_test/Costomer+OrderForm.csv")
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in data.columns:
    data.loc[:,feat]=le.fit_transform(data.loc[:,feat])

In [5]:
data.head()

Phillippines  Indonesia  Malta  India
0             1          1      0      1
1             1          1      1      0
2             1          0      0      1
3             1          1      1      1
4             1          1      0      1

In [6]:
import scipy.stats as stats
stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])

F_onewayResult(statistic=1.286168556089167, pvalue=0.2776780955705948)

In [7]:
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(data)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 112.74730231885849.
p value is 1.0.
df is 897.
Expected table is 
[[0.74793008 0.73689052 0.7424103  0.77276909]
 [0.74793008 0.73689052 0.7424103  0.77276909]
 [0.49862006 0.49126035 0.4949402  0.51517939]
 ...
 [0.74793008 0.73689052 0.7424103  0.77276909]
 [0.99724011 0.9825207  0.9898804  1.03035879]
 [0.49862006 0.49126035 0.4949402  0.51517939]]
